import { Lead, Customer, Task, Profile, Notification } from './types'

export const mockProfile: Profile = {
  id: 'user_default_id',
  full_name: 'Alex Rivera',
  email: 'alex@orbitlabs.dev',
  business_name: 'OrbitLabs Tech',
  business_type: 'Software & Technology',
  phone: '+91 98765 43210',
  avatar_url: '',
  created_at: '2026-01-15T09:00:00.000Z',
}

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    user_id: 'user_default_id',
    name: 'Priya Sharma',
    email: 'priya@techvista.in',
    phone: '+91 98765 12345',
    source: 'Google Search',
    status: 'qualified',
    value: 250000,
    notes: 'Interested in enterprise subscription and custom integration.',
    created_at: '2026-06-13T09:00:00.000Z',
  },
  {
    id: 'lead-2',
    user_id: 'user_default_id',
    name: 'Rahul Mehta',
    email: 'rahul@nexagen.com',
    phone: '+91 87654 32109',
    source: 'LinkedIn',
    status: 'contacted',
    value: 150000,
    notes: 'Demo scheduled for next week. Very responsive.',
    created_at: '2026-06-10T09:00:00.000Z',
  },
  {
    id: 'lead-3',
    user_id: 'user_default_id',
    name: 'Ananya Desai',
    email: 'ananya@cloudpeak.io',
    phone: '+91 76543 21098',
    source: 'Referral',
    status: 'won',
    value: 480000,
    notes: 'Deal closed! Moving to onboarding phase.',
    created_at: '2026-06-06T09:00:00.000Z',
  },
  {
    id: 'lead-4',
    user_id: 'user_default_id',
    name: 'Vikram Patel',
    email: 'vikram@startupforge.in',
    phone: '+91 65432 10987',
    source: 'Instagram',
    status: 'new',
    value: 75000,
    notes: 'Requested info about starter plan. Early-stage startup.',
    created_at: '2026-06-17T09:00:00.000Z',
  },
  {
    id: 'lead-5',
    user_id: 'user_default_id',
    name: 'Neha Kapoor',
    email: 'neha@digitaledge.co',
    phone: '+91 54321 09876',
    source: 'LinkedIn',
    status: 'contacted',
    value: 320000,
    notes: 'Initial call completed. Setting up demo session.',
    created_at: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'lead-6',
    user_id: 'user_default_id',
    name: 'Arjun Reddy',
    email: 'arjun@innovate360.com',
    phone: '+91 43210 98765',
    source: 'Google Search',
    status: 'won',
    value: 180000,
    notes: 'Closed via promotional discount offer.',
    created_at: '2026-06-03T09:00:00.000Z',
  },
  {
    id: 'lead-7',
    user_id: 'user_default_id',
    name: 'Kavitha Nair',
    email: 'kavitha@greenlabs.org',
    phone: '+91 32109 87654',
    source: 'Referral',
    status: 'lost',
    value: 95000,
    notes: 'Went with a competitor. Budget constraints cited.',
    created_at: '2026-05-29T09:00:00.000Z',
  },
  {
    id: 'lead-8',
    user_id: 'user_default_id',
    name: 'Suresh Kumar',
    email: 'suresh@dataflow.tech',
    phone: '+91 21098 76543',
    source: 'Instagram',
    status: 'new',
    value: 420000,
    notes: 'High-value prospect. Needs enterprise features.',
    created_at: '2026-06-16T09:00:00.000Z',
  },
  {
    id: 'lead-9',
    user_id: 'user_default_id',
    name: 'Meera Joshi',
    email: 'meera@brightpath.in',
    phone: '+91 10987 65432',
    source: 'Google Search',
    status: 'qualified',
    value: 200000,
    notes: 'Passed qualification. Proposal being prepared.',
    created_at: '2026-06-14T09:00:00.000Z',
  },
  {
    id: 'lead-10',
    user_id: 'user_default_id',
    name: 'Deepak Agarwal',
    email: 'deepak@scaleworks.co',
    phone: '+91 09876 54321',
    source: 'LinkedIn',
    status: 'lost',
    value: 60000,
    notes: 'Not the right fit for their current needs.',
    created_at: '2026-05-25T09:00:00.000Z',
  },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    user_id: 'user_default_id',
    name: 'Ananya Desai',
    email: 'ananya@cloudpeak.io',
    phone: '+91 76543 21098',
    company: 'CloudPeak Solutions',
    revenue_generated: 480000,
    notes: 'Premium client. Signed annual enterprise contract.',
    created_at: '2026-06-06T09:00:00.000Z',
  },
  {
    id: 'cust-2',
    user_id: 'user_default_id',
    name: 'Arjun Reddy',
    email: 'arjun@innovate360.com',
    phone: '+91 43210 98765',
    company: 'Innovate 360',
    revenue_generated: 180000,
    notes: 'Growth plan subscriber. Loves the AI assistant feature.',
    created_at: '2026-06-03T09:00:00.000Z',
  },
  {
    id: 'cust-3',
    user_id: 'user_default_id',
    name: 'Sanjay Verma',
    email: 'sanjay@bharatlogistics.in',
    phone: '+91 99887 76655',
    company: 'Bharat Logistics',
    revenue_generated: 750000,
    notes: 'Largest account. Multi-department deployment.',
    created_at: '2026-04-15T09:00:00.000Z',
  },
  {
    id: 'cust-4',
    user_id: 'user_default_id',
    name: 'Pooja Menon',
    email: 'pooja@creativemind.co',
    phone: '+91 88776 65544',
    company: 'CreativeMind Agency',
    revenue_generated: 120000,
    notes: 'Starter plan. Potential upsell candidate.',
    created_at: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'cust-5',
    user_id: 'user_default_id',
    name: 'Amit Choudhary',
    email: 'amit@finserv.in',
    phone: '+91 77665 54433',
    company: 'FinServ Capital',
    revenue_generated: 350000,
    notes: 'Financial services vertical. Compliance-focused.',
    created_at: '2026-03-10T09:00:00.000Z',
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    user_id: 'user_default_id',
    title: 'Review CloudPeak proposal',
    description: 'Go over the enterprise pricing details and customize the integration timeline.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-06-19',
    created_at: '2026-06-16T09:00:00.000Z',
  },
  {
    id: 'task-2',
    user_id: 'user_default_id',
    title: 'Prepare monthly AI insights report',
    description: 'Analyze lead pipeline metrics and generate actionable business feedback.',
    priority: 'medium',
    status: 'pending',
    due_date: '2026-06-21',
    created_at: '2026-06-17T09:00:00.000Z',
  },
  {
    id: 'task-3',
    user_id: 'user_default_id',
    title: 'Onboard Bharat Logistics',
    description: 'Set up multi-department access and configure data pipelines.',
    priority: 'high',
    status: 'completed',
    due_date: '2026-06-16',
    created_at: '2026-06-13T09:00:00.000Z',
  },
  {
    id: 'task-4',
    user_id: 'user_default_id',
    title: 'Update payment gateway integration',
    description: 'Test Razorpay sandbox transactions and update API endpoints.',
    priority: 'medium',
    status: 'pending',
    due_date: '2026-06-23',
    created_at: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'task-5',
    user_id: 'user_default_id',
    title: 'Follow up with Neha Kapoor',
    description: 'Send demo recording and custom pricing proposal.',
    priority: 'high',
    status: 'pending',
    due_date: '2026-06-20',
    created_at: '2026-06-18T09:00:00.000Z',
  },
  {
    id: 'task-6',
    user_id: 'user_default_id',
    title: 'Audit marketing channel performance',
    description: 'Compare ROI across Instagram, LinkedIn, and Google ads.',
    priority: 'low',
    status: 'completed',
    due_date: '2026-06-14',
    created_at: '2026-06-12T09:00:00.000Z',
  },
  {
    id: 'task-7',
    user_id: 'user_default_id',
    title: 'Draft Q2 client newsletter',
    description: 'Highlight new AI features and success stories.',
    priority: 'low',
    status: 'pending',
    due_date: '2026-06-25',
    created_at: '2026-06-17T09:00:00.000Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'New lead captured',
    description: 'Suresh Kumar from DataFlow Tech submitted a contact form.',
    read: false,
    timestamp: '2026-06-18T08:30:00.000Z',
    type: 'lead',
  },
  {
    id: 'notif-2',
    title: 'Task due tomorrow',
    description: 'Review CloudPeak proposal is due on June 19.',
    read: false,
    timestamp: '2026-06-18T07:00:00.000Z',
    type: 'task',
  },
  {
    id: 'notif-3',
    title: 'Deal closed!',
    description: 'Ananya Desai signed the enterprise contract worth ₹4,80,000.',
    read: true,
    timestamp: '2026-06-17T16:00:00.000Z',
    type: 'customer',
  },
  {
    id: 'notif-4',
    title: 'System update',
    description: 'Operon V1.0 is now live with AI assistant features.',
    read: true,
    timestamp: '2026-06-16T10:00:00.000Z',
    type: 'system',
  },
]

export const mockRevenueData = [
  { month: 'Jan', revenue: 320000 },
  { month: 'Feb', revenue: 450000 },
  { month: 'Mar', revenue: 380000 },
  { month: 'Apr', revenue: 520000 },
  { month: 'May', revenue: 610000 },
  { month: 'Jun', revenue: 780000 },
]

export const mockLeadTrendData = [
  { month: 'Jan', new: 12, won: 4, lost: 2 },
  { month: 'Feb', new: 18, won: 7, lost: 3 },
  { month: 'Mar', new: 15, won: 5, lost: 4 },
  { month: 'Apr', new: 22, won: 9, lost: 2 },
  { month: 'May', new: 28, won: 11, lost: 5 },
  { month: 'Jun', new: 24, won: 8, lost: 3 },
]

export const mockActivities = [
  { id: 'act-1', description: 'Suresh Kumar submitted a contact form', type: 'lead' as const, timestamp: '2026-06-18T08:30:00.000Z' },
  { id: 'act-2', description: 'Ananya Desai signed enterprise contract', type: 'customer' as const, timestamp: '2026-06-17T16:00:00.000Z' },
  { id: 'act-3', description: 'Task "Onboard Bharat Logistics" completed', type: 'task' as const, timestamp: '2026-06-16T14:00:00.000Z' },
  { id: 'act-4', description: 'Neha Kapoor moved to "Contacted" stage', type: 'lead' as const, timestamp: '2026-06-15T11:00:00.000Z' },
  { id: 'act-5', description: 'New lead from Instagram: Vikram Patel', type: 'lead' as const, timestamp: '2026-06-14T09:00:00.000Z' },
  { id: 'act-6', description: 'Monthly AI insights report generated', type: 'task' as const, timestamp: '2026-06-13T15:00:00.000Z' },
  { id: 'act-7', description: 'Arjun Reddy upgraded to Growth plan', type: 'customer' as const, timestamp: '2026-06-12T10:00:00.000Z' },
  { id: 'act-8', description: 'Kavitha Nair marked as lost', type: 'lead' as const, timestamp: '2026-06-11T13:00:00.000Z' },
]

/** Placeholder AI responses keyed by category */
export const aiResponses: Record<string, string[]> = {
  default: [
    "Based on your current pipeline data, I'd recommend focusing on the 3 qualified leads in your funnel. Your conversion rate from qualified to won is strong at 62%, so nurturing these leads should yield ₹6-8 lakhs in the next 30 days.",
    "I've analyzed your recent activity patterns. Your team's response time to new leads averages 4.2 hours. Industry benchmark is under 1 hour. Reducing this could improve your conversion rate by 15-20%.",
    "Your top-performing lead source is Google Search with a 34% conversion rate, followed by Referrals at 28%. Consider allocating more marketing budget to these channels.",
  ],
  followup: [
    "Here's a follow-up message draft:\n\nHi [Name],\n\nThank you for taking the time to explore Operon. I wanted to follow up on our conversation about your business needs.\n\nI've prepared a customized proposal that addresses the key areas we discussed:\n\n• Automated lead management\n• AI-powered customer insights\n• Revenue tracking dashboard\n\nWould you be available for a 15-minute call this week to walk through it?\n\nBest regards,\nAlex Rivera\nOrbitLabs Tech",
    "Here's a re-engagement message:\n\nHi [Name],\n\nI noticed it's been a while since we last connected. I wanted to share some exciting updates:\n\n• New AI assistant for business insights\n• Enhanced lead scoring algorithm\n• Mobile-responsive dashboard\n\nI think these features could really benefit your business. Would love to catch up when you have a moment.\n\nWarm regards,\nAlex",
  ],
  sales: [
    "Based on your sales data analysis:\n\n📊 **Pipeline Summary**\n- Total Pipeline Value: ₹22,30,000\n- Weighted Pipeline: ₹14,50,000\n- Average Deal Size: ₹2,23,000\n\n💡 **Recommendations:**\n1. Focus on Priya Sharma and Meera Joshi — both are qualified and showing high engagement\n2. Consider a time-limited offer for Suresh Kumar to accelerate the ₹4,20,000 deal\n3. Schedule a win-back call with Kavitha Nair — the competitor they chose recently raised prices",
    "Your monthly revenue trend shows strong growth:\n\n• MoM Growth: +27.8%\n• Best Month: June (₹7,80,000)\n• YTD Revenue: ₹30,60,000\n\nAt this trajectory, you're on track to hit ₹1 Cr annual revenue by Q3. Key actions:\n1. Upsell existing Growth plan customers\n2. Launch referral incentive program\n3. Target enterprises in the FinTech vertical",
  ],
}
